os:
  - linux
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: required
before_install:
  - sudo apt-get install -qq hdf5-tools libhdf5-serial-dev
install:
  - pip install .
script:
  - ./run_test_travis.sh
