os:
  - linux
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y hdf5-tools libhdf5-serial-dev libbz2-dev liblzma-dev libcurl4-openssl-dev python3-dev python-dev python3-pip python-pip
  - sudo pip3 install --upgrade pip  
  - sudo pip2 install --upgrade pip
install:
  - pip3 install . --ignore-installed six
  - pip2 install . --ignore-installed six
script:
  - ./run_test_travis.sh
