os:
  - linx
  - osx
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: required
addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - hdf5-tools
install:
  - pip install .
script:
  - ./run_test_travis.sh
