version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04 
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y hdf5-tools libhdf5-serial-dev libbz2-dev liblzma-dev python3-pip
      - checkout
      - run: |
          pip3 install .
          bash run_test_travis.sh
