version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04 
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y hdf5-tools libhdf5-serial-dev
      - checkout
      - run: |
          bash run_test_travis.sh
